import {
  faArrowDown,
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowUpRightFromSquare,
  faBackward,
  faCrosshairs,
  faDrum,
  faEye,
  faEyeSlash,
  faFilter,
  faForward,
  faGuitar,
  faLocationDot,
  faPen,
  faPlus,
  faQuestion,
  faRoute,
  faSortDown,
  faSortUp,
  faStar,
  faTrashCan,
  faVolumeHigh,
  faVolumeXmark,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import { faEar, faEarDeaf } from "@fortawesome/pro-regular-svg-icons";

export {
  faArrowDown,
  faArrowLeft,
  faArrowRightFromBracket,
  faArrowUpRightFromSquare,
  faBackward,
  faCrosshairs,
  faDrum,
  faEar,
  faEarDeaf,
  faEye,
  faEyeSlash,
  faFilter,
  faForward,
  faGuitar,
  faLocationDot,
  faPen,
  faPlus,
  faQuestion,
  faRoute,
  faSortDown,
  faSortUp,
  faStar,
  faTrashCan,
  faVolumeHigh,
  faVolumeXmark,
  faXmark,
};
